version: 2.1
orbs:
  ruby: circleci/ruby@2.0.0
  docker: circleci/docker@2.2.0

jobs:
  test:
    docker:
      - image: cimg/ruby:2.7

    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test:
          include: spec/**/*_spec.rb

workflows:
  test:
    jobs:
      - test

  build-and-publish-docker-image:
    jobs:
      - docker/publish:
          image: darkphnx/ical-filter-proxy
